INSERT INTO ER_COMPANIES(COMP_ID, SUBS_ID) VALUES(1, 0);
INSERT INTO KM_CASH_FLOWS(COMP_ID, CAFL_DATE_CREATED, CAFL_DATE_END, CAFL_NAME, CAFL_BUBGETED_AMOUNT, CAFL_REVIEW_AMOUNT) VALUES (1,'2012-10-03', '2012-12-31', 'test cash flow #1', 30000, 29000);
INSERT INTO KM_CASH_FLOWS(COMP_ID, CAFL_DATE_CREATED, CAFL_DATE_END, CAFL_NAME, CAFL_BUBGETED_AMOUNT, CAFL_REVIEW_AMOUNT) VALUES (1,'2012-10-04', '2012-12-31', 'test cash flow #2', 45000, 19000);
INSERT INTO KM_CASH_FLOWS(COMP_ID, CAFL_DATE_CREATED, CAFL_DATE_END, CAFL_NAME, CAFL_BUBGETED_AMOUNT, CAFL_REVIEW_AMOUNT) VALUES (1,'2012-10-05', '2012-12-31', 'test cash flow #3', 55000, 59000);
INSERT INTO KM_CASH_FLOWS(COMP_ID, CAFL_DATE_CREATED, CAFL_DATE_END, CAFL_NAME, CAFL_BUBGETED_AMOUNT, CAFL_REVIEW_AMOUNT) VALUES (1,'2012-10-06', '2012-12-31', 'test cash flow #4', 65000, 62000);

BEGIN;
SET CONSTRAINTS ALL DEFERRED;
INSERT INTO KM_TRANSACTION_GROUPS(CAFL_ID, TRGR_PARENT_ID, TRGT_ID, TRGR_NAME,TRGR_PRINT_ORDER, TRGR_PRINT_TOTAL, TRGR_IMPORT_RULES)
      VALUES                     (1      , 2             , 0      , 'Τραπ. Λογ' , 2            , false , 'import rules for transaction group 2'); 
INSERT INTO KM_TRANSACTION_GROUPS(CAFL_ID, TRGR_PARENT_ID, TRGT_ID, TRGR_NAME,TRGR_PRINT_ORDER, TRGR_PRINT_TOTAL, TRGR_IMPORT_RULES)
      VALUES                     (1      , NULL          , 0      , 'Ταμείο' , 1               , false , 'import rules for transaction group 1');
END;


INSERT INTO KM_TRANSACTION_GROUPS_TEMPLATE  (COMP_ID, TRGR_PARENT_ID, TRGT_ID, TRGE_NAME,TRGE_PRINT_ORDER, TRGE_PRINT_TOTAL, TRGE_IMPORT_RULES)
      VALUES                                (1      , NULL          , 0      , 'Ταμείο' , 1               , false , 'import rules for transaction group 1');
INSERT INTO KM_TRANSACTION_GROUPS_TEMPLATE  (COMP_ID, TRGR_PARENT_ID, TRGT_ID, TRGE_NAME,TRGE_PRINT_ORDER, TRGE_PRINT_TOTAL, TRGE_IMPORT_RULES)
      VALUES                                (1      , NULL             , 0      , 'Τραπ. Λογ' , 2            , false , 'import rules for transaction group 2'); 
