INSERT INTO "AA_SUBSCRIPTIONS"("SUBS_NAME") VALUES('foo');
-- the various user passwords are encoding using the SHA-256 algorithm, 1M iterations, with the indicated salt
-- unhashed passwords are: bill/gatesfoo, james/the_king, mary/bones, jack/paranoid


INSERT INTO "AA_USERS"("SUBS_ID", "USER_NAME", "USER_PASSWORD", "USER_PASSWORD_SALT", "USER_FIRSTNAME", "USER_SURNAME", "USER_EMAIL") (SELECT max("SUBS_ID"), 'bill' , 'a603d7fea04d4ae942b9828c41c0f19761d8868a50046c53664a7b69bf357286' , 'foo', 'Bill' , 'Gates', 'foo@gmail.com'   FROM "AA_SUBSCRIPTIONS");
INSERT INTO "AA_USERS"("SUBS_ID", "USER_NAME", "USER_PASSWORD", "USER_PASSWORD_SALT", "USER_FIRSTNAME", "USER_SURNAME", "USER_EMAIL") (SELECT max("SUBS_ID"), 'james', 'd50ffcd0b397b3ddf3814b9256c8f3149ee5517d85b13bc9c967217a828483c0' , 'foo', 'James', 'Stewart', 'foo@gmail.com'  FROM "AA_SUBSCRIPTIONS");
INSERT INTO "AA_USERS"("SUBS_ID", "USER_NAME", "USER_PASSWORD", "USER_PASSWORD_SALT", "USER_FIRSTNAME", "USER_SURNAME", "USER_EMAIL") (SELECT max("SUBS_ID"), 'mary' , '553277b52de90ca45ed8a689a24019ba1eb31bee9555806c0cb8a1cc06c4feb5' , 'foo', 'Mary' , 'Bones', 'foo@gmail.com'    FROM "AA_SUBSCRIPTIONS");
INSERT INTO "AA_USERS"("SUBS_ID", "USER_NAME", "USER_PASSWORD", "USER_PASSWORD_SALT", "USER_FIRSTNAME", "USER_SURNAME", "USER_EMAIL") (SELECT max("SUBS_ID"), 'jack' , '256179882f18c58616eeb27e28d04ccb31ccc6bb44a1a977a314415201682a2f' , 'foo', 'Jack' , 'Paranoid', 'foo@gmail.com' FROM "AA_SUBSCRIPTIONS");

INSERT INTO "SS_SYSTEM_ELEMENTS"("SYEL_DESCRIPTION") VALUES('secure');
INSERT INTO "SS_SYSTEM_ELEMENTS"("SYEL_DESCRIPTION") VALUES('can_cache');


INSERT INTO "SS_ROLES"("SUBS_ID", "ROLE_CAPTION") (SELECT max("SUBS_ID"), 'staff'  FROM "SS_SUBSCRIPTIONS");
INSERT INTO "SS_ROLES"("SUBS_ID", "ROLE_CAPTION") (SELECT max("SUBS_ID"), 'cacher' FROM "SS_SUBSCRIPTIONS");
INSERT INTO "SS_ROLES"("SUBS_ID", "ROLE_CAPTION") (SELECT max("SUBS_ID"), 'admin'  FROM "SS_SUBSCRIPTIONS");
INSERT INTO "SS_ROLES"("SUBS_ID", "ROLE_CAPTION") (SELECT max("SUBS_ID"), 'user'   FROM "SS_SUBSCRIPTIONS");

INSERT INTO "SS_ROLE_ACCESS_RIGHTS"("ROLE_ID", "SYEL_ID") (SELECT a."ROLE_ID", b."SYEL_ID" FROM "SS_ROLES" a, "SS_SYSTEM_ELEMENTS" b WHERE a."ROLE_CAPTION"='staff' AND b."SYEL_DESCRIPTION"='secure');
INSERT INTO "SS_ROLE_ACCESS_RIGHTS"("ROLE_ID", "SYEL_ID") (SELECT a."ROLE_ID", b."SYEL_ID" FROM "SS_ROLES" a, "SS_SYSTEM_ELEMENTS" b WHERE a."ROLE_CAPTION"='cacher' AND b."SYEL_DESCRIPTION"='can_cache');
INSERT INTO "SS_ROLE_ACCESS_RIGHTS"("ROLE_ID", "SYEL_ID") (SELECT a."ROLE_ID", b."SYEL_ID" FROM "SS_ROLES" a, "SS_SYSTEM_ELEMENTS" b WHERE a."ROLE_CAPTION"='admin' AND b."SYEL_DESCRIPTION"='can_cache');

INSERT INTO "SS_USER_ROLES"("USER_ID", "ROLE_ID") (SELECT a."USER_ID", b."ROLE_ID" FROM "SS_USERS" a, "SS_ROLES" b WHERE a."USER_NAME"='bill'  AND  b."ROLE_CAPTION"='staff' );
INSERT INTO "SS_USER_ROLES"("USER_ID", "ROLE_ID") (SELECT a."USER_ID", b."ROLE_ID" FROM "SS_USERS" a, "SS_ROLES" b WHERE a."USER_NAME"='james' AND  b."ROLE_CAPTION"='admin' );
INSERT INTO "SS_USER_ROLES"("USER_ID", "ROLE_ID") (SELECT a."USER_ID", b."ROLE_ID" FROM "SS_USERS" a, "SS_ROLES" b WHERE a."USER_NAME"='mary'  AND  b."ROLE_CAPTION"='user'  );
INSERT INTO "SS_USER_ROLES"("USER_ID", "ROLE_ID") (SELECT a."USER_ID", b."ROLE_ID" FROM "SS_USERS" a, "SS_ROLES" b WHERE a."USER_NAME"='jack'  AND  b."ROLE_CAPTION"='cacher');
