SOURCE=conference-ornate-20min.en.tex
all:
	pdflatex $(SOURCE)
	pdflatex $(SOURCE)
clean:
	rm -f *.pdf
	rm -f *.log
	rm -f *.lol
	rm -f *.lof
	rm -f *.toc
	rm -f *.out
	rm -f *.aux
	rm -f *.nav
	rm -f *.snm
