INSERT INTO "SS_SUBSCRIPTIONS"("SUBS_NAME", "SUBS_DATABASE") VALUES('foo', 'foo');
-- the various user passwords are encoding using the SHA-256 algorithm, 1 iteration, with the indicated salt
-- unhashed passwords are: bill/gatesfoo, james/the_king, mary/bones, jack/paranoid


INSERT INTO "SS_USERS"("SUBS_ID", "USER_NAME", "USER_PASSWORD", "USER_PASSWORD_SALT", "USER_FIRSTNAME", "USER_SURNAME") (SELECT max("SUBS_ID"), 'bill' , '37ef5fa40c77bb36c70040ead6fa14e67bf254349e5cb4152dff98a5b75d0ff9' , 'foo', 'Bill' , 'Gates'    FROM "SS_SUBSCRIPTIONS");
INSERT INTO "SS_USERS"("SUBS_ID", "USER_NAME", "USER_PASSWORD", "USER_PASSWORD_SALT", "USER_FIRSTNAME", "USER_SURNAME") (SELECT max("SUBS_ID"), 'james', '03f05f08db0100eec8a58bfb608ca4544b3569269effc48806fdc95f3d48bc77' , 'foo', 'James', 'Stewart'  FROM "SS_SUBSCRIPTIONS");
INSERT INTO "SS_USERS"("SUBS_ID", "USER_NAME", "USER_PASSWORD", "USER_PASSWORD_SALT", "USER_FIRSTNAME", "USER_SURNAME") (SELECT max("SUBS_ID"), 'mary' , 'b6ab062a29136baf0106a20ac031ac0141424673a223957e879eaa2bcebe57cf' , 'foo', 'Mary' , 'Bones'    FROM "SS_SUBSCRIPTIONS");
INSERT INTO "SS_USERS"("SUBS_ID", "USER_NAME", "USER_PASSWORD", "USER_PASSWORD_SALT", "USER_FIRSTNAME", "USER_SURNAME") (SELECT max("SUBS_ID"), 'jack' , 'd16dcbc8de82ff5dd6ccf77222881d41a019cbf0474f3cb7a41ba3bf7e0036e1' , 'foo', 'Jack' , 'Paranoid' FROM "SS_SUBSCRIPTIONS");

INSERT INTO "SS_SYSTEM_ELEMENTS"("SYEL_DESCRIPTION") VALUES('secure');
INSERT INTO "SS_SYSTEM_ELEMENTS"("SYEL_DESCRIPTION") VALUES('can_cache');


INSERT INTO "SS_ROLES"("SUBS_ID", "ROLE_CAPTION") (SELECT max("SUBS_ID"), 'staff'  FROM "SS_SUBSCRIPTIONS");
INSERT INTO "SS_ROLES"("SUBS_ID", "ROLE_CAPTION") (SELECT max("SUBS_ID"), 'cacher' FROM "SS_SUBSCRIPTIONS");
INSERT INTO "SS_ROLES"("SUBS_ID", "ROLE_CAPTION") (SELECT max("SUBS_ID"), 'admin'  FROM "SS_SUBSCRIPTIONS");
INSERT INTO "SS_ROLES"("SUBS_ID", "ROLE_CAPTION") (SELECT max("SUBS_ID"), 'user'   FROM "SS_SUBSCRIPTIONS");

INSERT INTO "SS_ROLE_ACCESS_RIGHTS"("ROLE_ID", "SYEL_ID") (SELECT a."ROLE_ID", b."SYEL_ID" FROM "SS_ROLES" a, "SS_SYSTEM_ELEMENTS" b WHERE a."ROLE_CAPTION"='staff' AND b."SYEL_DESCRIPTION"='secure');
INSERT INTO "SS_ROLE_ACCESS_RIGHTS"("ROLE_ID", "SYEL_ID") (SELECT a."ROLE_ID", b."SYEL_ID" FROM "SS_ROLES" a, "SS_SYSTEM_ELEMENTS" b WHERE a."ROLE_CAPTION"='cacher' AND b."SYEL_DESCRIPTION"='can_cache');
INSERT INTO "SS_ROLE_ACCESS_RIGHTS"("ROLE_ID", "SYEL_ID") (SELECT a."ROLE_ID", b."SYEL_ID" FROM "SS_ROLES" a, "SS_SYSTEM_ELEMENTS" b WHERE a."ROLE_CAPTION"='admin' AND b."SYEL_DESCRIPTION"='can_cache');

INSERT INTO "SS_USER_ROLES"("USER_ID", "ROLE_ID") (SELECT a."USER_ID", b."ROLE_ID" FROM "SS_USERS" a, "SS_ROLES" b WHERE a."USER_NAME"='bill'  AND  b."ROLE_CAPTION"='staff' );
INSERT INTO "SS_USER_ROLES"("USER_ID", "ROLE_ID") (SELECT a."USER_ID", b."ROLE_ID" FROM "SS_USERS" a, "SS_ROLES" b WHERE a."USER_NAME"='james' AND  b."ROLE_CAPTION"='admin' );
INSERT INTO "SS_USER_ROLES"("USER_ID", "ROLE_ID") (SELECT a."USER_ID", b."ROLE_ID" FROM "SS_USERS" a, "SS_ROLES" b WHERE a."USER_NAME"='mary'  AND  b."ROLE_CAPTION"='user'  );
INSERT INTO "SS_USER_ROLES"("USER_ID", "ROLE_ID") (SELECT a."USER_ID", b."ROLE_ID" FROM "SS_USERS" a, "SS_ROLES" b WHERE a."USER_NAME"='jack'  AND  b."ROLE_CAPTION"='cacher');
