/*
Created: 11/9/2012
Modified: 25/9/2012
Model: 01.Γνώση Διοίκησης
Database: PostgreSQL 9.1
*/

-- Create sequences section -------------------------------------------------

CREATE SEQUENCE CACA_ID_seq
 INCREMENT BY 1
 NO MAXVALUE
 NO MINVALUE
 CACHE 1;

CREATE SEQUENCE CAGR_ID_seq
 INCREMENT BY 1
 NO MAXVALUE
 NO MINVALUE
 CACHE 1;

CREATE SEQUENCE CATR_ID_seq
 INCREMENT BY 1
 NO MAXVALUE
 NO MINVALUE
 CACHE 1;

CREATE SEQUENCE CCIS_ID_seq
 INCREMENT BY 1
 NO MAXVALUE
 NO MINVALUE
 CACHE 1;

CREATE SEQUENCE REAC_ID_seq
 INCREMENT BY 1
 NO MAXVALUE
 NO MINVALUE
 CACHE 1;

CREATE SEQUENCE REAG_ID_seq
 INCREMENT BY 1
 NO MAXVALUE
 NO MINVALUE
 CACHE 1;

CREATE SEQUENCE CAFL_ID_seq
 INCREMENT BY 1
 NO MAXVALUE
 NO MINVALUE
 CACHE 1;

-- Create tables section -------------------------------------------------

-- Table KM_CACH_TRANSACTIONS

CREATE TABLE KM_CACH_TRANSACTIONS(
 CATR_ID Integer DEFAULT nextval('CATR_ID_seq'::regclass) NOT NULL,
 CAFL_ID Integer NOT NULL,
 REAC_ID Integer NOT NULL,
 CACA_ID Integer NOT NULL,
 CATR_DATE Date DEFAULT now() NOT NULL,
 CATR_VALUE Money DEFAULT 0 NOT NULL,
 CATR_DESCRIPTION Character varying(120) NOT NULL,
 CATR_IS_MANUAL Boolean DEFAULT true NOT NULL,
 CATR_IS_PROACTIVE Boolean DEFAULT false NOT NULL,
 CATR_DATE_CREATED Date DEFAULT now() NOT NULL
)
WITH (OIDS=FALSE);

COMMENT ON TABLE KM_CACH_TRANSACTIONS IS 'Τα transactions (οι εγγραφές)';
COMMENT ON COLUMN KM_CACH_TRANSACTIONS.CACA_ID IS 'Cash Account Category Affected by thiw Transaction';
COMMENT ON COLUMN KM_CACH_TRANSACTIONS.CATR_DATE IS 'Ημερομηνία Είσπραξης/Πληρωμής';
COMMENT ON COLUMN KM_CACH_TRANSACTIONS.CATR_VALUE IS 'Αξία Κίνησης';
COMMENT ON COLUMN KM_CACH_TRANSACTIONS.CATR_DESCRIPTION IS 'Αιτιολογία Κίνησης';
COMMENT ON COLUMN KM_CACH_TRANSACTIONS.CATR_IS_MANUAL IS 'Δείκτης πληκτρολογούμενης ή Αυτόματης Κίνησης 
true = πληκτρολογούμενη,
false = Αυτόματα από ERP ή Function';
COMMENT ON COLUMN KM_CACH_TRANSACTIONS.CATR_IS_PROACTIVE IS 'Τύπος Εγγραφής 
0 = Προυπολογιστική, 
1 = Aπολογιστική';
COMMENT ON COLUMN KM_CACH_TRANSACTIONS.CATR_DATE_CREATED IS 'Ημερομηνία εισαγωγής της εγγραφής';

-- Add keys for table KM_CACH_TRANSACTIONS

ALTER TABLE KM_CACH_TRANSACTIONS ADD CONSTRAINT CATR_PK PRIMARY KEY (CATR_ID);

-- Table KM_CASH_CATEGORIES

CREATE TABLE KM_CASH_CATEGORIES(
 CACA_ID Integer DEFAULT nextval('CACA_ID_seq'::regclass) NOT NULL,
 CAGR_ID Integer NOT NULL,
 CACA_DESCRIPTION Character varying(120) NOT NULL,
 CCIS_ID Integer NOT NULL,
 CACA_IMPORTVALUES Character varying(1000) NOT NULL
)
WITH (OIDS=FALSE);

COMMENT ON TABLE KM_CASH_CATEGORIES IS 'Κατηγορίες Διαθεσίμων π.χ.Ταμείο (στο Group Διαθέσιμα)';
COMMENT ON COLUMN KM_CASH_CATEGORIES.CACA_DESCRIPTION IS 'Περιγραφή Κατηγορίας Είσπραξης Πληρωμής Διαθεσήμων';
COMMENT ON COLUMN KM_CASH_CATEGORIES.CCIS_ID IS 'Δείκτης εάν θα διαβάσει από Γεν.Λογιστική, από το εμπορικό, πληκτρολογουμενο  
1= Πληκτρολογούμενο, 
2=Γ.Λ, 
3=Εμπορικό';
COMMENT ON COLUMN KM_CASH_CATEGORIES.CACA_IMPORTVALUES IS 'Λογαριασμός η Function ανάλογα με το εαν πρόκειται για λογαριασμό βάζουμε <3800>+<3801> εάν πρόκειται για Function το όνομά της';

-- Add keys for table KM_CASH_CATEGORIES

ALTER TABLE KM_CASH_CATEGORIES ADD CONSTRAINT CACA_PK PRIMARY KEY (CACA_ID);

-- Table KM_CASH_CATEGORIES_INPUT_SOURC

CREATE TABLE KM_CASH_CATEGORIES_INPUT_SOURC(
 CCIS_ID Integer DEFAULT nextval('CCIS_ID_seq'::regclass) NOT NULL,
 CCIS_NAME Character varying(60)
)
WITH (OIDS=FALSE);

COMMENT ON TABLE KM_CASH_CATEGORIES_INPUT_SOURC IS 'LOOKUP TABLE. input source type for cash categories';

-- Add keys for table KM_CASH_CATEGORIES_INPUT_SOURC

ALTER TABLE KM_CASH_CATEGORIES_INPUT_SOURC ADD CONSTRAINT CCIS_PK PRIMARY KEY (CCIS_ID);

-- Table KM_CASH_GROUPS

CREATE TABLE KM_CASH_GROUPS(
 CAGR_ID Integer DEFAULT nextval('CAGR_ID_seq'::regclass) NOT NULL,
 COMP_ID Integer NOT NULL,
 CAGR_DESCRIPTION Character varying(120) NOT NULL,
 CAGR_PRINT_ORDER Smallint,
 CAGR_PRINT_TOTAL Smallint
)
WITH (OIDS=FALSE);

COMMENT ON TABLE KM_CASH_GROUPS IS 'Σύνολα κατηγοριών από τις κατηγορίες π.χ. Διαθέσημα';
COMMENT ON COLUMN KM_CASH_GROUPS.CAGR_DESCRIPTION IS 'Περιγραφή Ομαδοποίησης Κατηγοριών Εισπράξεων/Πληρωμών';
COMMENT ON COLUMN KM_CASH_GROUPS.CAGR_PRINT_ORDER IS 'Η σειρά εκτύπωσης των ομάδων στην ταμειακή κατάσταση';
COMMENT ON COLUMN KM_CASH_GROUPS.CAGR_PRINT_TOTAL IS 'Δεικτης για το  εάν στην εκτύπωση της ταμειακής κατάστασης θα τυπώνονται σύνολα στην Ομάδα
0 = χωρίς εκτύπωση συνόλων
1 = με εκτύπωση συνόλων';

-- Add keys for table KM_CASH_GROUPS

ALTER TABLE KM_CASH_GROUPS ADD CONSTRAINT CAGR_PK PRIMARY KEY (CAGR_ID);

-- Table KM_REVENUE_EXPENSE_ACCOUNT_CAT

CREATE TABLE KM_REVENUE_EXPENSE_ACCOUNT_CAT(
 REAC_ID Integer DEFAULT nextval('REAC_ID_seq'::regclass) NOT NULL,
 REAG_ID Integer NOT NULL,
 REAC_DESCRIPTION Character varying(120) NOT NULL,
 REAC_IS_EXPENSE Boolean DEFAULT true NOT NULL,
 CCIS_ID Integer DEFAULT 0 NOT NULL,
 REAC_IMPORT_RULES Character varying(1000) NOT NULL
)
WITH (OIDS=FALSE);

COMMENT ON TABLE KM_REVENUE_EXPENSE_ACCOUNT_CAT IS 'Κατηγορίες Διαθεσίμων π.χ.Ταμείο (στο Group Διαθέσιμα)';
COMMENT ON COLUMN KM_REVENUE_EXPENSE_ACCOUNT_CAT.REAC_DESCRIPTION IS 'Περιγραφή Κατηγορίας Είσπραξης Πληρωμής Διαθεσήμων';
COMMENT ON COLUMN KM_REVENUE_EXPENSE_ACCOUNT_CAT.REAC_IS_EXPENSE IS 'false = Είσπραξη, true = Πληρωμή';
COMMENT ON COLUMN KM_REVENUE_EXPENSE_ACCOUNT_CAT.CCIS_ID IS 'Δείκτης εάν θα διαβάσει από Γεν.Λογιστική, από το εμπορικό, πληκτρολογουμενο  
1= Πληκτρολογούμενο, 
2=Γ.Λ, 
3=Εμπορικό';
COMMENT ON COLUMN KM_REVENUE_EXPENSE_ACCOUNT_CAT.REAC_IMPORT_RULES IS 'Λογαριασμός η Function ανάλογα με το εαν πρόκειται για λογαριασμό βάζουμε <3800>+<3801> εάν πρόκειται για Function το όνομά της';

-- Add keys for table KM_REVENUE_EXPENSE_ACCOUNT_CAT

ALTER TABLE KM_REVENUE_EXPENSE_ACCOUNT_CAT ADD CONSTRAINT REAC_PK PRIMARY KEY (REAC_ID);

-- Table KM_REVENUE_EXPENSE_ACCOUNT_GRO

CREATE TABLE KM_REVENUE_EXPENSE_ACCOUNT_GRO(
 REAG_ID Integer DEFAULT nextval('REAG_ID_seq'::regclass) NOT NULL,
 COMP_ID Integer NOT NULL,
 REAG_DESCRIPTION Character varying(120) NOT NULL,
 REAG_PRINT_SEQUENCE Smallint,
 REAG_MUST_PRINT_TOTAL Boolean DEFAULT false
)
WITH (OIDS=FALSE);

COMMENT ON TABLE KM_REVENUE_EXPENSE_ACCOUNT_GRO IS 'Σύνολα κατηγοριών από τις κατηγορίες π.χ. Διαθέσημα';
COMMENT ON COLUMN KM_REVENUE_EXPENSE_ACCOUNT_GRO.REAG_DESCRIPTION IS 'Περιγραφή Ομαδοποίησης Κατηγοριών Εισπράξεων/Πληρωμών';
COMMENT ON COLUMN KM_REVENUE_EXPENSE_ACCOUNT_GRO.REAG_PRINT_SEQUENCE IS 'Η σειρά εκτύπωσης των ομάδων στην ταμειακή κατάσταση';
COMMENT ON COLUMN KM_REVENUE_EXPENSE_ACCOUNT_GRO.REAG_MUST_PRINT_TOTAL IS 'Δεικτης για το εάν στην εκτύπωση της ταμειακής κατάστασης θα τυπώνονται σύνολα στην Ομάδα
FALSE = χωρίς εκτύπωση συνόλων
TRUE = με εκτύπωση συνόλων';

-- Add keys for table KM_REVENUE_EXPENSE_ACCOUNT_GRO

ALTER TABLE KM_REVENUE_EXPENSE_ACCOUNT_GRO ADD CONSTRAINT REAG_PK PRIMARY KEY (REAG_ID);

-- Table ER_COMPANIES

CREATE TABLE ER_COMPANIES(
 COMP_ID Integer NOT NULL,
 SUBS_ID Integer NOT NULL
)
WITH (OIDS=FALSE);

-- Add keys for table ER_COMPANIES

ALTER TABLE ER_COMPANIES ADD CONSTRAINT COMP_PK PRIMARY KEY (COMP_ID);

-- Table KM_CASH_FLOWS

CREATE TABLE KM_CASH_FLOWS(
 CAFL_ID Integer DEFAULT nextval('CAFL_ID_seq'::regclass) NOT NULL,
 SUBS_ID Integer,
 COMP_ID Integer,
 CAFL_DATE_CREATED Date,
 CAFL_DATE_END Date,
 CAFL_COMMENTS Character varying(1000)
)
WITH (OIDS=FALSE);

COMMENT ON TABLE KM_CASH_FLOWS IS 'TABLE THAT HOLDS ALL CASH FLOW SCHEDULING FROM THIS SUBSCRIBER';

-- Add keys for table KM_CASH_FLOWS

ALTER TABLE KM_CASH_FLOWS ADD CONSTRAINT CAFL_PK PRIMARY KEY (CAFL_ID);

-- Create relationships section ------------------------------------------------- 

ALTER TABLE KM_CASH_CATEGORIES ADD CONSTRAINT CAGR_CACA_FK FOREIGN KEY (CAGR_ID) REFERENCES KM_CASH_GROUPS (CAGR_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE KM_CASH_CATEGORIES ADD CONSTRAINT CCIS_CACA_FK FOREIGN KEY (CCIS_ID) REFERENCES KM_CASH_CATEGORIES_INPUT_SOURC (CCIS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE KM_CACH_TRANSACTIONS ADD CONSTRAINT CACA_CATR_FK FOREIGN KEY (CACA_ID) REFERENCES KM_CASH_CATEGORIES (CACA_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE KM_CACH_TRANSACTIONS ADD CONSTRAINT REAG_CATR_FK FOREIGN KEY (REAC_ID) REFERENCES KM_REVENUE_EXPENSE_ACCOUNT_CAT (REAC_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE KM_REVENUE_EXPENSE_ACCOUNT_CAT ADD CONSTRAINT CCIS_REAC_FK FOREIGN KEY (CCIS_ID) REFERENCES KM_CASH_CATEGORIES_INPUT_SOURC (CCIS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE KM_REVENUE_EXPENSE_ACCOUNT_CAT ADD CONSTRAINT REAG_REAC_FK FOREIGN KEY (REAG_ID) REFERENCES KM_REVENUE_EXPENSE_ACCOUNT_GRO (REAG_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE KM_CASH_GROUPS ADD CONSTRAINT COMP_CAGR_FK FOREIGN KEY (COMP_ID) REFERENCES ER_COMPANIES (COMP_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE KM_REVENUE_EXPENSE_ACCOUNT_GRO ADD CONSTRAINT COMP_REAG_FK FOREIGN KEY (COMP_ID) REFERENCES ER_COMPANIES (COMP_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE KM_CASH_FLOWS ADD CONSTRAINT COMP_CAFL_FK FOREIGN KEY (COMP_ID) REFERENCES ER_COMPANIES (COMP_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE KM_CACH_TRANSACTIONS ADD CONSTRAINT CAFL_CATR_FK FOREIGN KEY (CAFL_ID) REFERENCES KM_CASH_FLOWS (CAFL_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER SEQUENCE CACA_ID_seq OWNED BY KM_CASH_CATEGORIES.CACA_ID;
ALTER SEQUENCE CAGR_ID_seq OWNED BY KM_CASH_GROUPS.CAGR_ID;
ALTER SEQUENCE CATR_ID_seq OWNED BY KM_CACH_TRANSACTIONS.CATR_ID;
ALTER SEQUENCE CCIS_ID_seq OWNED BY KM_CASH_CATEGORIES_INPUT_SOURC.CCIS_ID;
ALTER SEQUENCE REAC_ID_seq OWNED BY KM_REVENUE_EXPENSE_ACCOUNT_CAT.REAC_ID;
ALTER SEQUENCE REAG_ID_seq OWNED BY KM_REVENUE_EXPENSE_ACCOUNT_GRO.REAG_ID;
ALTER SEQUENCE CAFL_ID_seq OWNED BY KM_CASH_FLOWS.CAFL_ID;

